name = "hvacr-contact-v1"
compatibility_date = "2026-06-01"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "hvacr.contact", custom_domain = true },
  { pattern = "www.hvacr.contact", custom_domain = true }
]

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
